"""empty message

Revision ID: 10a2447610ae
Revises: e38ec81d5195
Create Date: 2020-05-09 06:10:27.365205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a2447610ae'
down_revision = 'e38ec81d5195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_lists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_lists', 'completed')
    # ### end Alembic commands ###
